config/routes.rb
Rails.application.routes.draw do
  resources :grades
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  # root'home#index'
  resources :profiles
  resources :home
  resources :welcome
  resources :courses do
    resources :materials, only: [:index, :new, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end
   resources :messages
  
  resources :questions do
    resources :comments
  end
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:index,:show] 
  resources :relationships, only: [:create, :destroy]
  get '/search', to: 'users#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  
  paginates_per 6
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name:'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'
    # One conversation is one-to-many that contains lots of messages.
    has_many :messages, dependent: :destroy
  
    # Set validation to prevent [: sender_id,: recipient_id] from being saved in the same combination.
    validates_uniqueness_of :sender_id, scope: :recipient_id
  
    # Explained below
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
  
    # Explained below
    def target_user(current_user)
      if sender_id == current_user.id
        User.find(recipient_id)
      elsif recipient_id == current_user.id
        User.find(sender_id)
      end
    end

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :grades, dependent: :destroy 
  has_many :questions, dependent: :destroy 
  has_many :materials, dependent: :destroy 
  validates :name, presence: true
  validates :credit, presence: true
  validates :code, presence: true
  paginates_per 5
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :course
  validates :names, presence: true, length: {maximum: 40}
  validates :student_id, presence: true,length: { minimum: 5, maximum: 5}
  # uniqueness: true, 
  before_save :calculate_and_save_average
  def calculate_and_save_average
    assignments=(self.assignment_1+self.assignment_2+self.assignment_3)/3
    quizes=(self.quiz_1+self.quiz_2+self.quiz_3)/3
    self.out_of_100=(quizes + assignments + self. mid_exam + self.final_exam).round(2)
    self.out_of_20= (self.out_of_100/5).round(2)
  end
  paginates_per 4
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :course
  mount_uploader :content, ContentUploader
  validates :title, presence: true
  validates :content, presence: true
  paginates_per 5
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :comments, dependent: :destroy 
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: {minimum: 2, maximum: 150}
  paginates_per 5
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :followed, class_name: "User"
belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 40}
  validates :phone, uniqueness: true, length: {minimum: 9, maximum: 13}
  # validates :student_id, uniqueness: true, length: { minimum: 5, maximum: 5}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :comments, dependent: :destroy 
         has_many :courses, dependent: :destroy 
         has_many :questions, dependent: :destroy 
         has_one  :profile
         has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
         has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower
        
        
         def follow!(other_user)
          active_relationships.create!(followed_id: other_user.id)
        end
        
        #Check whether you are following
        def following?(other_user)
          active_relationships.find_by(followed_id: other_user.id)
        end
        def unfollow!(other_user)
          active_relationships.find_by(followed_id: other_user.id).destroy
        end
        
        paginates_per 5
        
        end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @search = Question.search(params[:q])
    @questions =@search.result.order("created_at DESC").page(params[:page])
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = current_user.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :image, :user_id, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
    :user
end
def resource
    @resource ||=User.new
end
def resource_class
    User
end
def devise_mapping
    @devise_mapping ||=Devise.devise_mapping[:user]
end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/questions/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap Sign in Form with Circular Social Buttons</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #434343;
	background: #dfe7e9;
	font-family: 'Varela Round', sans-serif;
}
.form-control {
	font-size: 16px;
	transition: all 0.4s;
	box-shadow: none;
}
.form-control:focus {
	border-color: #5cb85c;
}
.form-control, .btn {
	border-radius: 50px;
	outline: none !important;
}
.signin-form {
	width: 600px;
	margin: 0 auto;
  padding: 30px 0;
  margin-bottom: 5rem;
  margin-top: 5rem;
}
.signin-form form {
	border-radius: 5px;
	margin-bottom: 20px;
	background: #fff;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 40px;
}
.signin-form a {
	color: #5cb85c;
}    
.signin-form h2 {
	text-align: center;
	font-size: 34px;
	margin: 10px 0 15px;
}
.signin-form .hint-text {
	color: #999;
	text-align: center;
	margin-bottom: 20px;
}
.signin-form .form-group {
	margin-bottom: 20px;
}
.signin-form .btn {        
	font-size: 18px;
	line-height: 26px;        
	font-weight: bold;
	text-align: center;
}
.signin-form .small {
	font-size: 13px;
}
.signin-btn {
	text-align: center;
	border-color: #5cb85c;
	transition: all 0.4s;
}
.signin-btn:hover {
	background: #5cb85c;
	opacity: 0.8;
}
.or-seperator {
	margin: 50px 0 15px;
	text-align: center;
	border-top: 1px solid #e0e0e0;
}
.or-seperator b {
	padding: 0 10px;
	width: 40px;
	height: 40px;
	font-size: 16px;
	text-align: center;
	line-height: 40px;
	background: #fff;
	display: inline-block;
	border: 1px solid #e0e0e0;
	border-radius: 50%;
	position: relative;
	top: -22px;
	z-index: 1;
}
.social-btn .btn {
	color: #fff;
	margin: 10px 0 0 30px;
	font-size: 15px;
	width: 55px;
	height: 55px;
	line-height: 45px;
	border-radius: 50%;
	font-weight: normal;
	text-align: center;
	border: none;
	transition: all 0.4s;
}	
.social-btn .btn:first-child {
	margin-left: 0;
}
.social-btn .btn:hover {
	opacity: 0.8;
}
</style>
</head>
<body>
<div class="signin-form">
<%= form_with(model: question, class:"signin-form", local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li style="color:red"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<h2>Ask A Question</h2>
		<div class="form-group">
		Course
		<%= form.collection_select :course_id, Course.all, :id, :name, class:"form-control input-lg" %>
		</div>
        <div class="form-group">
        <%= form.text_field :title, class:"form-control input-lg", placeholder:"Enter question's title" %>
        </div>
        <div class="form-group">
        <%= form.text_area :content, class:"form-control input-lg", placeholder:"Enter question's content" %>
        </div> 
        <div class="form-group">
         <%= form.file_field :image, class:"form-control input-lg" %>
		</div> 
        <div class="form-group">
        <%= form.hidden_field :user_id %>
        </div>
        <div class="form-group">
          <%= form.submit class:"btn btn-lg btn-block signin-btn", style:"background-color:#020031;color:#fff;" %>
        </div>
<% end %>
</div>
</body>
</html>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
  .cont{
  margin-bottom: 15rem;
  margin-top: 5rem;
  }

</style>
</head>
<body>

<%= search_form_for @search, class:"form-inline md-form mr-auto mb-4" do |f| %>  
<%= f.search_field :title_cont, class:"form-control mr-sm-2", placeholder:"Search" %>
<%= f.submit class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>
<center>
<div class="container">
<p style="margin-bottom:2rem"><%= link_to 'New Question', new_question_path, :"data-no-turbolink" => true, method: "get",class:"btn btn-outline-primary my-2 my-sm-0" %><p>
<div class="row">
<div class="col-md-8" style="margin-left:10rem;">
<div class="card">
<% if current_user.user_type == "Student" %>
<% @questions.each do |question| %>
  <% if user_signed_in? %>
  <% check = 0, links='1', id=nil%>
  <% Profile.all.each do |profile| %>
      <% check = 1%>
      <%links = question.user.profile.image.url if question.user.profile.present?%>
      <%id =profile%>
    <% end %>
  <% if check==1 %>
  <span style="color:white"></span>
  <p style="color:white"><%= image_tag links, class:"round" unless links.blank? %></p>
  <p><%= question.user.name %>--><%= link_to 'Start conversation', conversations_path(sender_id: current_user.id, recipient_id: question.user.id), method: :post, class:"btn btn-outline-primary my-2 my-sm-0" %>
  <%if  question.user.phone.present?%>
           <% @phone=question.user.phone %>
          <p> <%= link_to "https://api.whatsapp.com/send?phone= " + @phone  do %>
            <strong style="color:green">Chat On Whatsapp</strong>
          <% end %></p>
          <% end %>
  <% end %>
  </p>
  <% else %>
  <p><i class="fal fa-user"></i></p>
  <% end %>
  <% if question.image.url %>
    <%=  image_tag question.image.url, class:"card-img-top" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= question.title %></h5>
    <p class="card-text"><%= question.content %></p>
    <p class="card-text" style="color:green"> <i>Course<%= question.course.name %> <i></p>
  </div>
  <div class="card-footer">
    <small class="text-muted"><i class="fa fa-clock-o"></i><%=time_ago_in_words(question.created_at) %></small><br>
    <%= link_to 'show' , question, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-info my-2 my-sm-0" %>
    <%if user_signed_in?%>
    <% if current_user.id == question.user_id %>
    <%= link_to 'Edit', edit_question_path(question), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-warning my-2 my-sm-0" %>
    <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger my-2 my-sm-0" %>
    <% end %>
    <%= link_to 'add Comment', new_question_comment_path(question), :"data-no-turbolink" => true, method: "get",class:"btn btn-outline-success my-2 my-sm-0"%>
    <% end %>
    <%= question.comments.count%><%= link_to 'Comments', question_comments_path(question), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-secondary my-2 my-sm-0" %>
    </div><br>
  <% end %>
  <% else %>
<% if current_user.user_type=="Lecturer" %>
<% if current_user.courses.present? %>
<% current_user.courses.each do |cours| %>
  <% @c = cours.id %>
<% Question.where(course_id:@c).each do |question| %>
  <% if user_signed_in? %>
  <% check = 0, links='1', id=nil%>
  <% Profile.all.each do |profile| %>
      <% check = 1%>
      <%links = question.user.profile.image.url if question.user.profile.present?%>
      <%id =profile%>
    <% end %>
  <% if check==1 %>
  <span style="color:white"></span>
  <p style="color:white"><%= image_tag links, class:"round" unless links.blank? %></p>
  <p><%= question.user.name %>--><%= link_to 'Start conversation', conversations_path(sender_id: current_user.id, recipient_id: question.user.id), method: :post, class:"btn btn-outline-primary my-2 my-sm-0" %>
  <% end %>
  </p>
  <% else %>
  <p><i class="fal fa-user"></i></p>
  <% end %>
  <% if question.image.url %>
    <%=  image_tag question.image.url, class:"card-img-top" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= question.title %></h5>
    <p class="card-text"><%= question.content %></p>
    <p class="card-text" style="color:green"> <i>Course: <%= question.course.name %> <i></p>
  </div>
  <div class="card-footer">
    <small class="text-muted"><i class="fa fa-clock-o"></i><%= time_ago_in_words(question.created_at) %></small><br>
    <%= link_to 'show' , question, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-info my-2 my-sm-0" %>
    <%if user_signed_in?%>
    <% if current_user.id == question.user_id %>
    <%= link_to 'Edit', edit_question_path(question), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-warning my-2 my-sm-0" %>
    <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger my-2 my-sm-0" %>
    <% end %>
    <%= link_to 'add Comment', new_question_comment_path(question), :"data-no-turbolink" => true, method: "get",class:"btn btn-outline-success my-2 my-sm-0"%>
    <% end %>
    <%= question.comments.count%><%= link_to 'Comments', question_comments_path(question), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-secondary my-2 my-sm-0" %>
    </div><br>
  <% end %>



<% end %>
<% end %>
<% end %>
<% end %>
  </div>
  <hr>
  <%= paginate @questions %>

</div>
</div>
</div>
</center>
</body>
</html>

app/views/questions/new.html.erb
<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<div class="card-body">
<div class="row" style="color:white;">
  <div class="col-md-4">
    <% if  @question.image.url %>
    <%=  image_tag @question.image.url  %>
    <% end %>
  </div>
  <div class="col-md-8">
    <p class="card-text">
      <strong>Title:</strong>
    <%= @question.title %>
    </p>
    <p class="card-text">
      <strong>Content:</strong>
      <%= @question.content %>
    </p>
    <p class="card-text">
      <strong>User:</strong>
      <%= @question.user.email %>
    </p>
    <p style="margin-bottom:2rem;"><%= link_to 'Back', questions_path, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-dark my-2 my-sm-0" %></p>
  </div>
</div>
</div>