config/routes.rb
Rails.application.routes.draw do
  resources :grades
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  # root'home#index'
  resources :profiles
  resources :home
  resources :welcome
  resources :courses do
    resources :materials, only: [:index, :new, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end
   resources :messages
  
  resources :questions do
    resources :comments
  end
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:index,:show] 
  resources :relationships, only: [:create, :destroy]
  get '/search', to: 'users#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  
  paginates_per 6
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name:'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'
    # One conversation is one-to-many that contains lots of messages.
    has_many :messages, dependent: :destroy
  
    # Set validation to prevent [: sender_id,: recipient_id] from being saved in the same combination.
    validates_uniqueness_of :sender_id, scope: :recipient_id
  
    # Explained below
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
  
    # Explained below
    def target_user(current_user)
      if sender_id == current_user.id
        User.find(recipient_id)
      elsif recipient_id == current_user.id
        User.find(sender_id)
      end
    end

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :grades, dependent: :destroy 
  has_many :questions, dependent: :destroy 
  has_many :materials, dependent: :destroy 
  validates :name, presence: true
  validates :credit, presence: true
  validates :code, presence: true
  paginates_per 5
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :course
  validates :names, presence: true, length: {maximum: 40}
  validates :student_id, presence: true,length: { minimum: 5, maximum: 5}
  # uniqueness: true, 
  before_save :calculate_and_save_average
  def calculate_and_save_average
    assignments=(self.assignment_1+self.assignment_2+self.assignment_3)/3
    quizes=(self.quiz_1+self.quiz_2+self.quiz_3)/3
    self.out_of_100=(quizes + assignments + self. mid_exam + self.final_exam).round(2)
    self.out_of_20= (self.out_of_100/5).round(2)
  end
  paginates_per 4
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :course
  mount_uploader :content, ContentUploader
  validates :title, presence: true
  validates :content, presence: true
  paginates_per 5
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :comments, dependent: :destroy 
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: {minimum: 2, maximum: 150}
  paginates_per 5
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :followed, class_name: "User"
belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 40}
  validates :phone, uniqueness: true, length: {minimum: 9, maximum: 13}
  # validates :student_id, uniqueness: true, length: { minimum: 5, maximum: 5}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :comments, dependent: :destroy 
         has_many :courses, dependent: :destroy 
         has_many :questions, dependent: :destroy 
         has_one  :profile
         has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
         has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower
        
        
         def follow!(other_user)
          active_relationships.create!(followed_id: other_user.id)
        end
        
        #Check whether you are following
        def following?(other_user)
          active_relationships.find_by(followed_id: other_user.id)
        end
        def unfollow!(other_user)
          active_relationships.find_by(followed_id: other_user.id).destroy
        end
        
        paginates_per 5
        
        end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    
     @question =Question.find(params[:question_id])
    @comments = @question.comments.all.page(params[:page])
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @question =Question.find(params[:question_id])
    @comment = @question.comments.build
  end

  # GET /comments/1/edit
  def edit
   
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to questions_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end



  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      @question =Question.find(params[:question_id])
    @comment = @question.comments.find(params[:id])
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @question =Question.find(params[:question_id])
    @comment = @question.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :image, :user_id, :question_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
    :user
end
def resource
    @resource ||=User.new
end
def resource_class
    User
end
def devise_mapping
    @devise_mapping ||=Devise.devise_mapping[:user]
end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #434343;
	background: #dfe7e9;
	font-family: 'Varela Round', sans-serif;
}
.form-control {
	font-size: 16px;
	transition: all 0.4s;
	box-shadow: none;
}
.form-control:focus {
	border-color: #5cb85c;
}
.form-control, .btn {
	border-radius: 50px;
	outline: none !important;
}
.signin-form {
	width: 600px;
	margin: 0 auto;
  padding: 30px 0;
  margin-bottom: 5rem;
  margin-top: 5rem;
}
.signin-form form {
	border-radius: 5px;
	margin-bottom: 20px;
	background: #fff;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 40px;
}
.signin-form a {
	color: #5cb85c;
}    
.signin-form h2 {
	text-align: center;
	font-size: 34px;
	margin: 10px 0 15px;
}
.signin-form .hint-text {
	color: #999;
	text-align: center;
	margin-bottom: 20px;
}
.signin-form .form-group {
	margin-bottom: 20px;
}
.signin-form .btn {        
	font-size: 18px;
	line-height: 26px;        
	font-weight: bold;
	text-align: center;
}
.signin-form .small {
	font-size: 13px;
}
.signin-btn {
	text-align: center;
	border-color: #5cb85c;
	transition: all 0.4s;
}
.signin-btn:hover {
	background: #5cb85c;
	opacity: 0.8;
}
.or-seperator {
	margin: 50px 0 15px;
	text-align: center;
	border-top: 1px solid #e0e0e0;
}
.or-seperator b {
	padding: 0 10px;
	width: 40px;
	height: 40px;
	font-size: 16px;
	text-align: center;
	line-height: 40px;
	background: #fff;
	display: inline-block;
	border: 1px solid #e0e0e0;
	border-radius: 50%;
	position: relative;
	top: -22px;
	z-index: 1;
}
.social-btn .btn {
	color: #fff;
	margin: 10px 0 0 30px;
	font-size: 15px;
	width: 55px;
	height: 55px;
	line-height: 45px;
	border-radius: 50%;
	font-weight: normal;
	text-align: center;
	border: none;
	transition: all 0.4s;
}	
.social-btn .btn:first-child {
	margin-left: 0;
}
.social-btn .btn:hover {
	opacity: 0.8;
}
</style>
</head>
<body>
<div class="signin-form">
<%= form_for([@question, @question.comments.build]) do |form| %>
	<% if comment.errors.any? %>
	  <div id="error_explanation">
		<h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
		<ul>
		<% comment.errors.full_messages.each do |message| %>
		  <li><%= message %></li>
		<% end %>
		</ul>
	  </div>
	<% end %>
	 <h1 style="color:green"> Asked Question: <%= @question.title %></h1>
	 <br>
		<h2>Add Comment</h2>
		<div class="form-group">
		<%= form.text_area :title, class:"form-control input-lg", placeholder:"type comment", required: true %>
        </div>
		<div class="form-group">
		 <%= form.file_field :image, class:"form-control input-lg" %>
        </div> 
        <div class="form-group">
		<%  if user_signed_in? %>
		<%= form.hidden_field :user_id, value: current_user.id%>
		<% end %>
		</div>
		<div class="form-group">
		  <%= form.hidden_field:question_id %>
		</div>
        <div class="form-group">
          <%= form.submit 'Add Comment', class:"btn btn-lg btn-block signin-btn", style:"background-color:#020031;color:#fff;" %>
        </div>
<% end %>
</div>
</body>
</html>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<div>
  <div>
<h1>Comments</h1>

    <% @comments.each do |comment| %>
      <div class="col-lg-4 col-md-6 course-item">
      <% if user_signed_in? %>
  <% check = 0, links='1', id=nil%>
  <% Profile.all.each do |profile| %>
      <% check = 1%>
      <%links = comment.user.profile.image.url %>
      <%id =profile%>
    <% end %>
 <% if check==1 %>
 <span style="color:white"></span>
  <p style="color:white"><%= image_tag links, class:"round" unless links.blank? %> 
  <% end %>
  </p>
  <% else %>
  <p><i class="fal fa-user"></i></p>
 <% end %>
     <%= comment.user.name %>
        <div class="course-thumb">
        <% if comment.image.url %>
        <%=  image_tag comment.image.url%>
        <% end %>
          <div class="course-cat">
            <span><%= comment.title %></span>
          </div>
        </div>
        <div class="course-info">
          <div class="date"><i class="fa fa-clock-o"></i><%=time_ago_in_words(comment.created_at) %> ago</div>
          <p>Commented question:<%= comment.question.title %></p>
          <%= link_to 'Back', questions_path, :"data-no-turbolink" => true, method: "get", class:"btn btn-dark" %>
          <% if user_signed_in? %>
          <%if current_user.id==comment.user_id %>
          <% link_to 'Edit', [comment.question, comment], method: :edit, :"data-no-turbolink" => true, method: "get", class:"btn btn-warning" %>
           <%= link_to 'Delete', [comment.question, comment], method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
          <% end %>
          <% end %>
        </div>
      </div>
      <% end %>
      </div>
      </div>
<p style="text-align:center"><%= link_to 'add Comment', new_question_comment_path, :"data-no-turbolink" => true, method: "get", class:"btn btn-success" %></p>
<%= paginate @comments%>
</div>
</div>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

<%= link_to 'Back',  question_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @comment.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Question:</strong>
  <%= @comment.question %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment), :"data-no-turbolink" => true, method: "get"%> |
<%= link_to 'Back', comments_path, :"data-no-turbolink" => true, method: "get"%>