config/routes.rb
Rails.application.routes.draw do
  resources :grades
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  # root'home#index'
  resources :profiles
  resources :home
  resources :welcome
  resources :courses do
    resources :materials, only: [:index, :new, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end
   resources :messages
  
  resources :questions do
    resources :comments
  end
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:index,:show] 
  resources :relationships, only: [:create, :destroy]
  get '/search', to: 'users#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  
  paginates_per 6
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name:'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'
    # One conversation is one-to-many that contains lots of messages.
    has_many :messages, dependent: :destroy
  
    # Set validation to prevent [: sender_id,: recipient_id] from being saved in the same combination.
    validates_uniqueness_of :sender_id, scope: :recipient_id
  
    # Explained below
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
  
    # Explained below
    def target_user(current_user)
      if sender_id == current_user.id
        User.find(recipient_id)
      elsif recipient_id == current_user.id
        User.find(sender_id)
      end
    end

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :grades, dependent: :destroy 
  has_many :questions, dependent: :destroy 
  has_many :materials, dependent: :destroy 
  validates :name, presence: true
  validates :credit, presence: true
  validates :code, presence: true
  paginates_per 5
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :course
  validates :names, presence: true, length: {maximum: 40}
  validates :student_id, presence: true,length: { minimum: 5, maximum: 5}
  # uniqueness: true, 
  before_save :calculate_and_save_average
  def calculate_and_save_average
    assignments=(self.assignment_1+self.assignment_2+self.assignment_3)/3
    quizes=(self.quiz_1+self.quiz_2+self.quiz_3)/3
    self.out_of_100=(quizes + assignments + self. mid_exam + self.final_exam).round(2)
    self.out_of_20= (self.out_of_100/5).round(2)
  end
  paginates_per 4
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :course
  mount_uploader :content, ContentUploader
  validates :title, presence: true
  validates :content, presence: true
  paginates_per 5
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :comments, dependent: :destroy 
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: {minimum: 2, maximum: 150}
  paginates_per 5
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :followed, class_name: "User"
belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 40}
  validates :phone, uniqueness: true, length: {minimum: 9, maximum: 13}
  # validates :student_id, uniqueness: true, length: { minimum: 5, maximum: 5}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :comments, dependent: :destroy 
         has_many :courses, dependent: :destroy 
         has_many :questions, dependent: :destroy 
         has_one  :profile
         has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
         has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower
        
        
         def follow!(other_user)
          active_relationships.create!(followed_id: other_user.id)
        end
        
        #Check whether you are following
        def following?(other_user)
          active_relationships.find_by(followed_id: other_user.id)
        end
        def unfollow!(other_user)
          active_relationships.find_by(followed_id: other_user.id).destroy
        end
        
        paginates_per 5
        
        end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = current_user.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course =current_user.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:code, :name, :credit, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #434343;
	background: #dfe7e9;
	font-family: 'Varela Round', sans-serif;
}
.form-control {
	font-size: 16px;
	transition: all 0.4s;
	box-shadow: none;
}
.form-control:focus {
	border-color: #5cb85c;
}
.form-control, .btn {
	border-radius: 50px;
	outline: none !important;
}
.signin-form {
	width: 600px;
	margin: 0 auto;
  padding: 30px 0;
  margin-bottom: 5rem;
  margin-top: 5rem;
}
.signin-form form {
	border-radius: 5px;
	margin-bottom: 20px;
	background: #fff;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 40px;
}
.signin-form a {
	color: #5cb85c;
}    
.signin-form h2 {
	text-align: center;
	font-size: 34px;
	margin: 10px 0 15px;
}
.signin-form .hint-text {
	color: #999;
	text-align: center;
	margin-bottom: 20px;
}
.signin-form .form-group {
	margin-bottom: 20px;
}
.signin-form .btn {        
	font-size: 18px;
	line-height: 26px;        
	font-weight: bold;
	text-align: center;
}
.signin-form .small {
	font-size: 13px;
}
.signin-btn {
	text-align: center;
	border-color: #5cb85c;
	transition: all 0.4s;
}
.signin-btn:hover {
	background: #5cb85c;
	opacity: 0.8;
}
.or-seperator {
	margin: 50px 0 15px;
	text-align: center;
	border-top: 1px solid #e0e0e0;
}
.or-seperator b {
	padding: 0 10px;
	width: 40px;
	height: 40px;
	font-size: 16px;
	text-align: center;
	line-height: 40px;
	background: #fff;
	display: inline-block;
	border: 1px solid #e0e0e0;
	border-radius: 50%;
	position: relative;
	top: -22px;
	z-index: 1;
}
.social-btn .btn {
	color: #fff;
	margin: 10px 0 0 30px;
	font-size: 15px;
	width: 55px;
	height: 55px;
	line-height: 45px;
	border-radius: 50%;
	font-weight: normal;
	text-align: center;
	border: none;
	transition: all 0.4s;
}	
.social-btn .btn:first-child {
	margin-left: 0;
}
.social-btn .btn:hover {
	opacity: 0.8;
}
</style>
</head>
<body>
<div class="signin-form">
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li style="color:red"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<h2>Add Course</h2>
        <div class="form-group">
        <%= form.text_field :code, class:"form-control input-lg", placeholder:"Enter course code"%>
        </div>
        <div class="form-group">
         <%= form.text_field :name, class:"form-control input-lg", placeholder:"Enter course name" %>
        </div>
        <div class="form-group">
         <%= form.number_field :credit, class:"form-control input-lg", placeholder:"Enter course credit" %>
        </div> 
        <div class="form-group">
         <%= form.hidden_field :user_id %>
        </div>
        <div class="form-group">
          <%= form.submit 'Add Course', class:"btn btn-lg btn-block signin-btn", style:"background-color:#020031;color:#fff;" %>
        </div>
<% end %>
</div>
</body>
</html>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body style="background-color: white !important;">
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<style>
.table,.p{
  margin-bottom: 5rem;
  margin-top: 5rem;
  margin-left: 2rem;
  margin-right: 2rem;
}
.card {
        margin: 0 auto;
        float: none;
        margin-bottom: 10px; 
}

</style>
      <div class="card" style="width: 18rem;">
      <div class="card-header">
      Your Courses
      </div>
      <ul class="list-group list-group-flush">

      <% @courses.each do |course| %>
        <% if user_signed_in? %>
        <% if current_user.id == course.user_id %>
        <li class="list-group-item"><%= link_to course.name, course, :"data-no-turbolink" => true, method: "get"%></li>
        <%= link_to 'Download Excel report', grades_path(:course_id => course.id, format: :xlsx),class:"btn btn-outline-success my-2 my-sm-0" %>
          <% else %>
          <% if course.grades.present? %>
          <% course.grades.each do |grade| %>  
          <% if current_user.name == grade.names %>
          <li class="list-group-item"> <%=link_to course.name, course, :"data-no-turbolink" => true, method: "get"%></li>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
        </ul>
    </div>    
<% if current_user.user_type=="Lecturer" %>
<p class="p"><%= link_to 'New Course', new_course_path, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-success my-2 my-sm-0"%></p>
<% end %>
</body>
<br>


</html>

app/views/courses/new.html.erb
<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<body style="background-color: white !important">
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<style>
.table,.p{
  margin-bottom: 5rem;
  margin-top: 5rem;
  margin-left: 2rem;
  margin-right: 2rem;
}
</style>
<table class="table" >
  <thead class="thead-light">
    <tr>
      <th>Course code</th>
      <th>Name</th>
      <th>Credit</th>
      <th>Teacher</th>
      <th>Notes</th>
      <th>Marks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @course.code %></td>
        <td><%= @course.name %></td>
        <td><%= @course.credit %></td>
        <td><%= @course.user.name%></td>
        <td> <%= link_to 'Notes', course_materials_path(@course), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-info my-2 my-sm-0" %></td>
        <td><%= link_to 'Grades', grades_path(:course_id => @course.id), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-info my-2 my-sm-0" %></td>
        <% if current_user.id==@course.user_id %>
                <td><%= link_to 'Edit', edit_course_path(@course), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-warning my-2 my-sm-0"  %></td>
                <td><%= link_to 'Delete', @course, method: :delete, data: { confirm: 'Are you sure?' }, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-danger my-2 my-sm-0"  %></td>
                <td> <%= link_to 'upload notes', new_course_material_path(@course), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-success my-2 my-sm-0"  %></td>
                <td><%= link_to 'Record Marks', new_grade_path(:course_id => @course.id), :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-success my-2 my-sm-0"  %></td>
        <% end %>    
        </tr>
           
  </tbody>
</table>
<% if current_user.user_type=="Lecturer" %>
<p class="p"><%= link_to 'New Course', new_course_path, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-success my-2 my-sm-0"%></p>
<% end %>  
</body>
<br>

<p style="margin-bottom:2rem;text-align:center"><%= link_to 'Back', courses_path, :"data-no-turbolink" => true, method: "get", class:"btn btn-outline-dark my-2 my-sm-0" %></p>
<br>